import Head from "next/head";
import Image from "next/image";
import { Footer } from "../conponents/footer";
import { Links } from "../conponents/Links";
import styles from "../styles/Home.module.css";
import { Headline } from "./Headline";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Headline page="index" />

      <Links />

      <Footer />
    </div>
  );
}
